FROM node:16-alpine 

WORKDIR /app

COPY . .

RUN npm ci 

RUN npm run build

ENV NODE_ENV production

EXPOSE 3000

CMD [ "npx", "serve", "build" ]FROM node:latest

WORKDIR /app

COPY . .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]